//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace userClient.CRUDservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRUDservice.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/register", ReplyAction="*")]
        userClient.CRUDservice.registerResponse register(userClient.CRUDservice.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/register", ReplyAction="*")]
        System.Threading.Tasks.Task<userClient.CRUDservice.registerResponse> registerAsync(userClient.CRUDservice.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        userClient.CRUDservice.loginResponse login(userClient.CRUDservice.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<userClient.CRUDservice.loginResponse> loginAsync(userClient.CRUDservice.loginRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_info", ReplyAction="*")]
        userClient.CRUDservice.update_infoResponse update_info(userClient.CRUDservice.update_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update_info", ReplyAction="*")]
        System.Threading.Tasks.Task<userClient.CRUDservice.update_infoResponse> update_infoAsync(userClient.CRUDservice.update_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_info", ReplyAction="*")]
        userClient.CRUDservice.view_infoResponse view_info(userClient.CRUDservice.view_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/view_info", ReplyAction="*")]
        System.Threading.Tasks.Task<userClient.CRUDservice.view_infoResponse> view_infoAsync(userClient.CRUDservice.view_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveReading", ReplyAction="*")]
        void saveReading(int id, float blood_pressure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/saveReading", ReplyAction="*")]
        System.Threading.Tasks.Task saveReadingAsync(int id, float blood_pressure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bpReminder", ReplyAction="*")]
        System.DateTime bpReminder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bpReminder", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> bpReminderAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="register", Namespace="http://tempuri.org/", Order=0)]
        public userClient.CRUDservice.registerRequestBody Body;
        
        public registerRequest() {
        }
        
        public registerRequest(userClient.CRUDservice.registerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float blood_pressure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string password;
        
        public registerRequestBody() {
        }
        
        public registerRequestBody(string name, string gender, int age, float weight, float blood_pressure, string username, string password) {
            this.name = name;
            this.gender = gender;
            this.age = age;
            this.weight = weight;
            this.blood_pressure = blood_pressure;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerResponse", Namespace="http://tempuri.org/", Order=0)]
        public userClient.CRUDservice.registerResponseBody Body;
        
        public registerResponse() {
        }
        
        public registerResponse(userClient.CRUDservice.registerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class registerResponseBody {
        
        public registerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public userClient.CRUDservice.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(userClient.CRUDservice.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(int id, string username, string password) {
            this.id = id;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public userClient.CRUDservice.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(userClient.CRUDservice.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool loginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(bool loginResult, int id) {
            this.loginResult = loginResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class update_infoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update_info", Namespace="http://tempuri.org/", Order=0)]
        public userClient.CRUDservice.update_infoRequestBody Body;
        
        public update_infoRequest() {
        }
        
        public update_infoRequest(userClient.CRUDservice.update_infoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class update_infoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public float blood_pressure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string password;
        
        public update_infoRequestBody() {
        }
        
        public update_infoRequestBody(int id, string name, string gender, int age, float weight, float blood_pressure, string username, string password) {
            this.id = id;
            this.name = name;
            this.gender = gender;
            this.age = age;
            this.weight = weight;
            this.blood_pressure = blood_pressure;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class update_infoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update_infoResponse", Namespace="http://tempuri.org/", Order=0)]
        public userClient.CRUDservice.update_infoResponseBody Body;
        
        public update_infoResponse() {
        }
        
        public update_infoResponse(userClient.CRUDservice.update_infoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class update_infoResponseBody {
        
        public update_infoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class view_infoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="view_info", Namespace="http://tempuri.org/", Order=0)]
        public userClient.CRUDservice.view_infoRequestBody Body;
        
        public view_infoRequest() {
        }
        
        public view_infoRequest(userClient.CRUDservice.view_infoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class view_infoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double blood_pressure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string password;
        
        public view_infoRequestBody() {
        }
        
        public view_infoRequestBody(int id, string name, string gender, int age, double weight, double blood_pressure, string username, string password) {
            this.id = id;
            this.name = name;
            this.gender = gender;
            this.age = age;
            this.weight = weight;
            this.blood_pressure = blood_pressure;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class view_infoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="view_infoResponse", Namespace="http://tempuri.org/", Order=0)]
        public userClient.CRUDservice.view_infoResponseBody Body;
        
        public view_infoResponse() {
        }
        
        public view_infoResponse(userClient.CRUDservice.view_infoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class view_infoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double blood_pressure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string password;
        
        public view_infoResponseBody() {
        }
        
        public view_infoResponseBody(string name, string gender, int age, double weight, double blood_pressure, string username, string password) {
            this.name = name;
            this.gender = gender;
            this.age = age;
            this.weight = weight;
            this.blood_pressure = blood_pressure;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : userClient.CRUDservice.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<userClient.CRUDservice.WebService1Soap>, userClient.CRUDservice.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        userClient.CRUDservice.registerResponse userClient.CRUDservice.WebService1Soap.register(userClient.CRUDservice.registerRequest request) {
            return base.Channel.register(request);
        }
        
        public void register(string name, string gender, int age, float weight, float blood_pressure, string username, string password) {
            userClient.CRUDservice.registerRequest inValue = new userClient.CRUDservice.registerRequest();
            inValue.Body = new userClient.CRUDservice.registerRequestBody();
            inValue.Body.name = name;
            inValue.Body.gender = gender;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.blood_pressure = blood_pressure;
            inValue.Body.username = username;
            inValue.Body.password = password;
            userClient.CRUDservice.registerResponse retVal = ((userClient.CRUDservice.WebService1Soap)(this)).register(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<userClient.CRUDservice.registerResponse> userClient.CRUDservice.WebService1Soap.registerAsync(userClient.CRUDservice.registerRequest request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<userClient.CRUDservice.registerResponse> registerAsync(string name, string gender, int age, float weight, float blood_pressure, string username, string password) {
            userClient.CRUDservice.registerRequest inValue = new userClient.CRUDservice.registerRequest();
            inValue.Body = new userClient.CRUDservice.registerRequestBody();
            inValue.Body.name = name;
            inValue.Body.gender = gender;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.blood_pressure = blood_pressure;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((userClient.CRUDservice.WebService1Soap)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        userClient.CRUDservice.loginResponse userClient.CRUDservice.WebService1Soap.login(userClient.CRUDservice.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public bool login(ref int id, string username, string password) {
            userClient.CRUDservice.loginRequest inValue = new userClient.CRUDservice.loginRequest();
            inValue.Body = new userClient.CRUDservice.loginRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            userClient.CRUDservice.loginResponse retVal = ((userClient.CRUDservice.WebService1Soap)(this)).login(inValue);
            id = retVal.Body.id;
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<userClient.CRUDservice.loginResponse> userClient.CRUDservice.WebService1Soap.loginAsync(userClient.CRUDservice.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<userClient.CRUDservice.loginResponse> loginAsync(int id, string username, string password) {
            userClient.CRUDservice.loginRequest inValue = new userClient.CRUDservice.loginRequest();
            inValue.Body = new userClient.CRUDservice.loginRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((userClient.CRUDservice.WebService1Soap)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        userClient.CRUDservice.update_infoResponse userClient.CRUDservice.WebService1Soap.update_info(userClient.CRUDservice.update_infoRequest request) {
            return base.Channel.update_info(request);
        }
        
        public void update_info(int id, string name, string gender, int age, float weight, float blood_pressure, string username, string password) {
            userClient.CRUDservice.update_infoRequest inValue = new userClient.CRUDservice.update_infoRequest();
            inValue.Body = new userClient.CRUDservice.update_infoRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.gender = gender;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.blood_pressure = blood_pressure;
            inValue.Body.username = username;
            inValue.Body.password = password;
            userClient.CRUDservice.update_infoResponse retVal = ((userClient.CRUDservice.WebService1Soap)(this)).update_info(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<userClient.CRUDservice.update_infoResponse> userClient.CRUDservice.WebService1Soap.update_infoAsync(userClient.CRUDservice.update_infoRequest request) {
            return base.Channel.update_infoAsync(request);
        }
        
        public System.Threading.Tasks.Task<userClient.CRUDservice.update_infoResponse> update_infoAsync(int id, string name, string gender, int age, float weight, float blood_pressure, string username, string password) {
            userClient.CRUDservice.update_infoRequest inValue = new userClient.CRUDservice.update_infoRequest();
            inValue.Body = new userClient.CRUDservice.update_infoRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.gender = gender;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.blood_pressure = blood_pressure;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((userClient.CRUDservice.WebService1Soap)(this)).update_infoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        userClient.CRUDservice.view_infoResponse userClient.CRUDservice.WebService1Soap.view_info(userClient.CRUDservice.view_infoRequest request) {
            return base.Channel.view_info(request);
        }
        
        public void view_info(int id, ref string name, ref string gender, ref int age, ref double weight, ref double blood_pressure, ref string username, ref string password) {
            userClient.CRUDservice.view_infoRequest inValue = new userClient.CRUDservice.view_infoRequest();
            inValue.Body = new userClient.CRUDservice.view_infoRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.gender = gender;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.blood_pressure = blood_pressure;
            inValue.Body.username = username;
            inValue.Body.password = password;
            userClient.CRUDservice.view_infoResponse retVal = ((userClient.CRUDservice.WebService1Soap)(this)).view_info(inValue);
            name = retVal.Body.name;
            gender = retVal.Body.gender;
            age = retVal.Body.age;
            weight = retVal.Body.weight;
            blood_pressure = retVal.Body.blood_pressure;
            username = retVal.Body.username;
            password = retVal.Body.password;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<userClient.CRUDservice.view_infoResponse> userClient.CRUDservice.WebService1Soap.view_infoAsync(userClient.CRUDservice.view_infoRequest request) {
            return base.Channel.view_infoAsync(request);
        }
        
        public System.Threading.Tasks.Task<userClient.CRUDservice.view_infoResponse> view_infoAsync(int id, string name, string gender, int age, double weight, double blood_pressure, string username, string password) {
            userClient.CRUDservice.view_infoRequest inValue = new userClient.CRUDservice.view_infoRequest();
            inValue.Body = new userClient.CRUDservice.view_infoRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.gender = gender;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.blood_pressure = blood_pressure;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((userClient.CRUDservice.WebService1Soap)(this)).view_infoAsync(inValue);
        }
        
        public void saveReading(int id, float blood_pressure) {
            base.Channel.saveReading(id, blood_pressure);
        }
        
        public System.Threading.Tasks.Task saveReadingAsync(int id, float blood_pressure) {
            return base.Channel.saveReadingAsync(id, blood_pressure);
        }
        
        public System.DateTime bpReminder(int id) {
            return base.Channel.bpReminder(id);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> bpReminderAsync(int id) {
            return base.Channel.bpReminderAsync(id);
        }
    }
}
